Adjust header elements of deleted items to use an attribute
silverstripe-terraformers/open-archive-initiative pull request #18
Opened 2023-03-29 22:53 UTC by lianna-blanca

This change updates the `<header>` tag for deleted items, removing the element `<status>deleted</status>` and replacing it with attribute on the header element, `<header status="deleted">`.

Two unit tests have been added (content largely courtesy of @pjayme): GetRecordDocumentTest recreates the workflow of deleting an object, checking its header before and after, however because `generateDomElement()` (the function controlling the deletion markers) is a protected function, this test actually uses `processOaiRecord()`. The other test, OaiDcFormatterTest checks `generateDomElement()` directly.

2023-04-02 23:57 UTC, chrispenny requested changes
Awesome work! Thank you for picking this up.

I have a couple of minor suggestions, and you might need to chat with the CMS squad about the breakage with the linter:
https://github.com/silverstripe-terraformers/open-archive-initiative-repository/actions/runs/4558715230/jobs/8107598738?pr=18

Looks like maybe they changed something in the `silverstripe/cow` dependency.

If they're not able to help, then we can maybe disable the linter for now.

2023-04-02 23:57 UTC, chrispenny commented on tests/Documents/GetRecordDocumentTest.php
> +        $this->assertStringContainsString('<header>', $processedDocumentBody);
Expected output for a deleted record would include the new `status`.
```suggestion
        $this->assertStringContainsString('<header status="deleted">', $processedDocumentBody);
        // There should also be a non-deleted header element present.
        $this->assertStringContainsString('<header>', $processedDocumentBody);
```

2023-04-02 23:57 UTC, chrispenny commented on tests/Documents/GetRecordDocumentTest.php
> +        $this->assertStringNotContainsString("<status>deleted</status>", $processedDocumentBody);
First `assert` is covered above, and we don't need to assert that we're missing an element that we'll never assert does exist.
```suggestion
```

2023-04-02 23:57 UTC, chrispenny commented on tests/Documents/GetRecordDocumentTest.php
> +        $this->assertStringNotContainsString("<status>deleted</status>", $extractedDocumentBody);
Update to check that our header (with status) is not present.
```suggestion
$this->assertStringNotContainsString('<header status="deleted">', $processedDocumentBody);
```

2023-04-03 01:03 UTC, lianna-blanca commented on tests/Documents/GetRecordDocumentTest.php
> +$this->assertStringNotContainsString('<header status="deleted">', $processedDocumentBody);
```suggestion
        $this->assertStringContainsString('<datestamp>', $extractedDocumentBody);
        $this->assertStringNotContainsString('<header status="deleted">', $processedDocumentBody);
```

2023-04-03 03:00 UTC, chrispenny commented on tests/Formatters/OaiDcFormatterTest.php
> +    ];
Untested, but I think something like this should get passed the linter.
```suggestion
    /*
     * @phpcsSuppress SlevomatCodingStandard.TypeHints
     */
    protected static $required_extensions = [
        SiteTree::class => [
            VersionedOaiRecordManager::class,
            SiteTreeExtension::class,
        ],
    ];
```

2023-04-03 03:00 UTC, chrispenny commented on tests/Documents/GetRecordDocumentTest.php
> +    ];
I think...
```suggestion
    /*
     * @phpcsSuppress SlevomatCodingStandard.TypeHints
     */
    protected static $required_extensions = [
        SiteTree::class => [
            VersionedOaiRecordManager::class,
            SiteTreeExtension::class,
        ],
    ];
```

2023-04-03 20:11 UTC, merged